version: "3.9"

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fairness
    ports:
      - "5432:5432"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 3s
      timeout: 3s
      retries: 10

  flask_api:
    build: ./app
    container_name: flask_api
    ports:
      - "5050:5050"   # host:container
    depends_on:
      db:
        condition: service_healthy

  fairness_job:
    build: ./fairness_job
    container_name: fairness_job
    depends_on:
      db:
        condition: service_healthy

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
